### PR TITLE
clean up gradle file

### PR DESCRIPTION
**Pull request by jaredsburrows**

### CODE REVIEW

**Review by vanniktech — CHANGES_REQUESTED** [review]
Can you please leave compatibility with Java 7? I've had reports in the past that had problems using Java 8.

**Comment by jaredsburrows** [comment]
@vanniktech Fixed.

**Review by vanniktech — APPROVED** [review]

**Comment by jaredsburrows** [comment]
Odd, it looks like Travis is taking a long time to enqueue this build.

**Comment by vanniktech** [comment]
Yeah. I've got a few different builds and I think travis is limiting me. You can continue locally with this branch and then later just rebase.

**Pull request merged**
