### PR TITLE
Use spock for tests

### LINKED ISSUE #40: Use Spock for Testing
Site: http://spockframework.org/

Example: https://github.com/gradle/gradle/blob/master/subprojects/core/src/test/groovy/org/gradle/api/file/FileCollectionSymlinkTest.groovy

### PR DESCRIPTION
**Pull request by jaredsburrows**
@vanniktech fixes #40

### CODE REVIEW

**Comment by vanniktech** [comment]
This looks cool. Thanks a lot, I'll wait for CI and then merge

**Comment by jaredsburrows** [comment]
@vanniktech You had to manually merge to master? Didn't the build run last night?

**Comment by vanniktech** [comment]
It did though since the other PR got merged I updated this branch.

**Comment by jaredsburrows** [comment]
@vanniktech Awesome!

**Pull request merged**
