### PR TITLE
[Gradle] - Update dependencies

### PR DESCRIPTION
**Pull request by jaredsburrows**
@vanniktech

### CODE REVIEW

**Review by vanniktech — COMMENTED** [review]
Build is failing. I think a restart should do the trick.

**Comment by jaredsburrows** [comment]
@vanniktech It does not let me restart it for some reason.

**Comment by vanniktech** [comment]
Reopening does the trick.

**Comment by jaredsburrows** [comment]
@vanniktech Passed now :)

**Pull request merged**
